---
- name: TEST
  hosts: cat_sandbox
  user: admin
  gather_facts: False
  connection: local


  tasks:
      - name: enable interface
        netconf_config:
          host: 10.10.20.100
          hostkey_verify: False
          look_for_keys: False
          username: admin
          password: ciscopsdt
          xml: |
              <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
                  <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
                      <interface>
                          <name>GigabitEthernet2/1/4</name>
                          <enabled>true</enabled>
                      </interface>
                  </interfaces>
              </config>


      

