---
- name: TEST
  hosts: cat_sandbox
  connection: netconf


  tasks:
    - name: set ntp server in the device
      netconf_config:
        host: 10.10.20.100
        username: admin
        password: ciscopsdt
        xml: |
            <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
                <system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
                    <ntp>
                        <enabled>true</enabled>
                        <server>
                            <name>ntp1</name>
                            <udp><address>127.0.0.1</address></udp>
                        </server>
                    </ntp>
                </system>
            </config>

    - name: enable interface
      netconf_config:
        host: 10.10.20.100
        username: admin
        password: ciscopsdt
        xml: |
            <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
                <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
                    <interface>
                        <name>Te1/0/24</name>
                        <enabled>true</enabled>
                    </interface>
                </interfaces>
            </config>








      

